### ISSUE TITLE
cannot use imports in webpack

### ISSUE THREAD

**Issue by gdbd** [thread/react-static-render-plugin#2]
Hi, i am found your plugin very useful,
but i cant use it because my webpack.config.js cannot use import syntax used in plugin code:
"import path from "path";
import fs from "fs";" ...

with this error:
`
import path from "path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1050:16)
    at Module._compile (internal/modules/cjs/loader.js:1098:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)

`

other plugins used require syntax and work

how to use it in this case?

**Comment by stephencookdev** [comment]
We use webpack.config.babel.js internally (e.g. https://stackoverflow.com/a/31906902)

But this is a good point, we shouldn't use `import`s for an external facing plugin. We'll change to `require`, but you should be able to use https://stackoverflow.com/a/31906902 in the mean time :)
